autosite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from login.views import profile

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', include('mainpage.urls')),
    url(r'^register/', include('login.urls')),
    url(r'^profile/', profile),
    url(r'^forum/', include('forum.urls')),
    url(r'^', include('mainpage.urls')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
]

forum/urls.py
from django.conf.urls import url
from forum import views

urlpatterns = [
    url(r'^$', views.main),
    url(r'^add/$', views.add_comment),
]

mainpage/urls.py
from django.conf.urls import url
from mainpage import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^questions/$', views.questions),
    url(r'^questions/(?P<pk>[0-9]+)/$', views.get_one_question, name='get_one_question'),
    url(r'^questions/(?P<pk>\d+)/comment/$', views.add_comment_to_question, name='add_comment_to_question'),
    url(r'^articles/$', views.articles),
    url(r'^articles/(?P<pk>[0-9]+)/', views.get_one_article, name='get_one_article'),
    url(r'^questions/new/$', views.post_new, name='post_new'),
    url(r'^questions/(?P<pk>\d+)/get_comments/$', views.get_comments_for_question, name='get_comments_for_question'),

    #Login, Logout, Register
    url(r'^login/$', views.ajax_login, name='ajax_login'),
    url(r'^logout/$', views.ajax_logout, name='ajax_logout'),
]

mainpage/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth.models import User
from django.db import models
import datetime

class Banner(models.Model):
    banner_text = models.TextField('banner_text')

    def __str__(self):
        return self.banner_text.encode('utf8')

class ListItems(models.Model):
    title = models.TextField('title')

    def __str__(self):
        return self.title.encode('utf8')

class Item(models.Model):
    item_text = models.TextField('item_text')
    list_items = models.ForeignKey(ListItems, on_delete=models.CASCADE)


class Article(models.Model):
    article_title = models.TextField('article_title')
    article_short_description = models.TextField('short_description')
    article_text = models.TextField('article_text')
    article_date = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return self.article_title.encode('utf8')

class Question(models.Model):
    author_id = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.TextField('article_title')
    description = models.TextField('description')
    pub_date = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return self.title.encode('utf8')

class Comment(models.Model):
    author_id = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField('description')
    pub_date = models.DateTimeField(auto_now_add=True, blank=True)
    question_key = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.description.encode('utf8')

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    chat_access = models.BooleanField(default=False)

    def __unicode__(self):
        return unicode(self.user)

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

class Image_Link(models.Model):
    name = models.CharField(max_length=255)
    link = models.TextField('link')
    article_id = models.ForeignKey(Article, on_delete=models.CASCADE)

    def __str__(self):
        return self.name.encode('utf8')

mainpage/forms.py
from django import forms
from mainpage.models import Question, Comment

class QuestionForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = ('title', 'description',)

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('description',)

mainpage/views.py
from django.shortcuts import render, get_object_or_404
from mainpage.models import Banner, Article, ListItems, Item, Question, Comment, Image_Link
from mainpage.forms import QuestionForm, CommentForm
from django.template import Context, loader
from django.http import HttpResponse
import json
from django.shortcuts import redirect
from datetime import timedelta
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout

our_time_zone= timedelta(days=0, hours=3, seconds=0)

def articles(request):
    articles = Article.objects.order_by('id')[::-1]
    template = loader.get_template('mainpage/articles.html')
    context_dic = {}
    context_dic['user'] = request.user
    context_dic['articles'] = articles
    context = Context({'context_dic': context_dic})
    return HttpResponse(template.render(context))

def get_one_article(request, pk):
    article = get_object_or_404(Article, pk=pk)
    images = Image_Link.objects.all().filter(article_id=pk)
    template = loader.get_template('mainpage/article.html')
    context_dic = {}
    context_dic['user'] = request.user
    context_dic['article'] = article
    context_dic['images'] = images
    context = Context({'context_dic': context_dic})
    return HttpResponse(template.render(context))

def questions(request):
    questions = Question.objects.order_by('id')[::-1]
    template = loader.get_template('mainpage/questions.html')
    context_dic = {}
    context_dic['user'] = request.user
    context_dic['questions'] = questions
    context = Context({'context_dic': context_dic})
    return HttpResponse(template.render(context))

def get_one_question(request, pk):
    question = get_object_or_404(Question, pk=pk)
    comments = Comment.objects.all().filter(question_key=pk)
    template = loader.get_template('mainpage/show_question.html')
    context_dic = {}
    context_dic['question'] = question
    context_dic['comments'] = comments
    context_dic['user'] = request.user
    context_dic['form'] = CommentForm()
    context = Context({'context_dic': context_dic})
    return HttpResponse(template.render(context))

def get_comments_for_question(request, pk):
    comments = Comment.objects.all().filter(question_key=pk)
    data = [{'id': str(item.author_id), 'description': item.description, 'pub_date': (item.pub_date+our_time_zone).strftime('%Y %m %d %H %M')} for item in comments]
    print(data)
    return HttpResponse(json.dumps(data), content_type='application/json')

def add_comment_to_question(request, pk):
    question = get_object_or_404(Question, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.question_key = question
            comment.author_id = request.user
            comment.save()
            return redirect('mainpage.views.get_one_question', pk=question.pk)
    else:
        form = CommentForm()
    return render(request, 'mainpage/add_comment.html', {'form': form})

def index(request):
    banner_text = Banner.objects.order_by('id')[::-1]
    banner_text = banner_text[0]
    item_lists = ListItems.objects.all()
    items = []
    for i in item_lists:
        items.append(Item.objects.all().filter(list_items=i.id))
    context_dic = {}
    context_dic['user'] = request.user
    context_dic['banner_text'] = banner_text
    context_dic['item_lists'] = item_lists
    context_dic['items'] = items
    template = loader.get_template('mainpage/index.html')
    context = Context({'context_dic': context_dic})
    return HttpResponse(template.render(context))

def post_new(request):
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author_id = request.user
            question.save()
            return redirect('mainpage.views.get_one_question', pk=question.pk)
    else:
        form = QuestionForm()
    context_dic = {}
    context_dic['user'] = request.user
    context = Context({'context_dic': context_dic})
    return render(request, 'mainpage/question.html', {'form': form, 'context_dic': context_dic})

def ajax_login(request):
    username = request.POST['username']
    password = request.POST['password']
    print(username)
    print(password)
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            login(request, user)
            return HttpResponse("Success!")
        else:
            return HttpResponse("Fail!")
    else:
        return HttpResponse("You are invalid! This account not exist!")

def ajax_logout(request):
    logout(request)
    return HttpResponse("Success!")

mainpage/templates/mainpage/article.html
{% extends "mainpage/base.html" %}

{% block css-link %}
<link rel="stylesheet" type="text/css" href="/static/css/article.css">
{% endblock %}


{% block content %}
	 <!-- Статья -->
<div class="row article">
	<div class="col s10 offset-s1" >
		<div class="card white z-depth-2">
			<div class="card-content black-text">
				<span class="card-title">{{ context_dic.article.article_title }}</span>
				<p>{{ context_dic.article.article_text }}</p>
				<h6>{{ context_dic.article.article_date }}</h6>
			</div>
		</div>
		{% if context_dic.images %}
		<div class="col s12">
			<div class="card z-depth-2">
				<div class="card-content black-text">
					<h1>Картинки к статье: </h1>
					<div class="row">
					{% for image in context_dic.images %}
						<div class="col s3">
							<img class="materialboxed" data-caption="{{ image.name }}" width="200" src="{{ image.link }}">
						</div>
					{% endfor %}
					</div>
				</div>
			</div>
		</div>
		{% endif %}
	</div>
</div>
{% endblock %}

mainpage/templates/mainpage/articles.html
{% extends "mainpage/base.html" %}

{% block css-link %}
<link rel="stylesheet" type="text/css" href="/static/css/articles.css">
{% endblock %}

{% block content %}

<div class='row'>
	<div class="col s10 offset-s1 z-depth-3">
		<div class="card-panel cyan lighten-1">
			<h1 class="header-title">Статьи</h1>
		</div>

		{% for article in context_dic.articles %}
			<a href={% url 'get_one_article' pk=article.pk %}>
				<div class="row">
					<div class="col s8 offset-s2 no_ident bottom_margin">
						<div class="card cyan darken-3">
							<div class="card-content white-text">
								<span class="card-title">{{ article.article_title }}</span>
								<p>{{ article.article_short_description }}</p>
								<p>{{ article.article_date }}</p>
							</div>
						</div>
					</div>
				</div>
			</a>

		{% endfor %}
	</div>
</div>

{% endblock %}

mainpage/templates/mainpage/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="/static/css/materialize.css">
	<link rel="stylesheet" type="text/css" href="/static/css/mainpage.css">
	{% block css-link %}

	{% endblock %}
	<script src="/static/js/jquery-2.2.1.min.js"></script>
	<script src="/static/js/materialize.js"></script>
	<script src="/static/js/main.js"></script>
	<meta  name="keywords" content="Autosite">
	<meta name="description" content="Autosite">
	<meta http-equiv="content-language" content="ru">
	<title>Autosite</title>
</head>
<!-- Шапка-->
	<nav>
		<div class="nav-wrapper">
			<a href="/" class="brand-logo blue-text text-lighten-2"><img src="/static/img/Logo.png" class="logo-img"></a>
			<ul id="nav-mobile" class="right hide-on-med-and-down">
				<li><a class="waves-effect waves-light cyan darken-1 btn" href="/">Главная</a></li>
				<li><a class="waves-effect waves-light cyan darken-1 btn" href="/articles">Статьи</a></li>
				<li><a class="waves-effect waves-light cyan darken-1 btn" href="/questions">Вопросы/ответы</a></li>
				<li><a class="waves-effect waves-light cyan darken-1 btn" href="/forum">Чат</a></li>
				{% if context_dic.user.is_authenticated %}
				<li><a class="waves-effect waves-light teal darken-1 btn" href="/profile">Профиль</a></li>
				<li><a class="waves-effect waves-light btn" id="ajax_logout">Выход</a></li>
				{% else %}
				<li><a class="waves-effect waves-light btn modal-trigger" href="#modal_login">Вход</a></li>
				<li><a class="blue-text text-lighten-2" href="/register">Регистрация</a></li>
				{% endif %}
			</ul>
		</div>
	</nav>

	<!-- Вход -->
	<div id="modal_login" class="modal">
		<div class="modal-content">
			<h4>Вход через соцсети:</h4>
			<a class="waves-effect waves-light btn" href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}">Google</a>
			<a class="waves-effect waves-light btn" href="{% url 'social:begin' 'vk-oauth2' %}?next={{ request.path }}">VK</a>
			<a class="waves-effect waves-light btn" href="{% url 'social:begin' 'twitter' %}?next={{ request.path }}">Twitter</a>
		</div>

		<div class="modal-footer">
			<hr>
		</div>

		<div class="modal-content">
			<h4>Вход через сайт:</h4>
			<div class="input-field col s6">
				<input id="id_username" name="username" type="text" class="validate">
				<label for="first_name">Логин</label>
			</div>
			<div class="input-field col s6">
				<input id="id_password" name="password" type="text" class="validate">
				<label for="last_name">Пароль</label>
			</div>
		</div>
		<div class="modal-footer">
			<input type="button" value="Login" id="ajax_login" class="waves-effect waves-light modal-action modal-close waves-effect waves-green btn-flat"/>
		</div>
	</div>

	<div class="content">
	{% block content %}

	{% endblock %}
	</div>

	</body>
		<footer class="page-footer teal lighten-2">
			<div class="container">
				<div class="row">
					<div class="col l6 s12">
						<h5 class="white-text"><p>АААА, здесь большой заголовок</p></h5>
						<p class="grey-text text-lighten-4">Здесь что-то будет</p>
					</div>
				<div class="col l4 offset-l2 s12">
					<h5 class="white-text">Ссылки</h5>
					<ul>
						<li><a class="grey-text text-lighten-3" href="/articles">Статьи</a></li>
						<li><a class="grey-text text-lighten-3" href="/questions">Вопросы/ответы</a></li>
						<li><a class="grey-text text-lighten-3" href="/">Форум</a></li>
						<li><a class="grey-text text-lighten-3" href="#!">О нас</a></li>
					</ul>
				</div>
			</div>
		</div>
		<div class="footer-copyright">
			<div class="container">
				&copy; Alexander Smirnov, 2016 ¯\_(ツ)_/¯
				<a class="grey-text text-lighten-4 right" href="#!">( ͡° ͜ʖ ͡°)</a>
			</div>
		</div>
	</footer>
</html>

mainpage/templates/mainpage/index.html
{% extends "mainpage/base.html" %}

{% block css-link %}
<link rel="stylesheet" type="text/css" href="/static/css/content.css">
{% endblock %}

{% block content %}

	 <!-- Банер -->
<div class="row banner-img">
	<div class="col s6 offset-s3 banner-card">
		<div class="card-panel teal">
			<span class="white-text">{{ context_dic.banner_text.banner_text }}</span>
		</div>
	</div>
</div>

<div class="main_text">
	<div class="row">
		<div class="col s12 m12 l12">
			<div class="card white">
				<div class="card-content black-text">
					<span class="card-title center">Ремонт и техническое обслуживание вашего автомобиля</span>
					<p>Приглашаем посетить мастерскую по обслуживанию и ремонту легковых автомобилей в п. Усть-Донецком.Опыт работы с автомобилями составляет более 15-ти лет. Качество, надежность и профессионализм - это принципы нашей работы.  Мастер   всегда рад проконсультировать клиента о неисправностях, особенностях обслуживания или текущем ремонте автомобиля. Основной концепцией в работе и дальнейшем развитии мы считаем доступность автосервиса, где качественно и недорого делают работу с максимально лояльным отношением к клиенту.</p>
				</div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col s12 m12 l12 ">
			{% for item_list in context_dic.item_lists %}
			<ul class="collection with-header">
				<li class="collection-header">
					<h4>{{ item_list.title }} </h4>
				</li>
				{% for items in context_dic.items %}
					{% for item in items %}
						{% if item.list_items.id = item_list.id %}
						<li class="collection-item">{{ item.item_text }}</li>
						{% endif %}
					{% endfor %}
				{% endfor %}
			</ul>
			{% endfor %}
		</div>
	</div>

	<div class="row">
		<div class="col s12 m12 l12 ">
			<div class="card white darken-1 z-depth-3">
				<div class="card-content black-text">
					<span class="card-title">Время работы:</span>
					<p>График работы автосервиса: с 9 до 18, если необходимо отремонтировать авто в другое время, то по предварительному звонку</p>
				</div>
			</div>
		</div>
	</div>

	<div class="row google_map">
		<div class="col s6 offset-s3 google_map">
			<div class="card white darken-1 z-depth-3 google_map">
				<div class="card-content black-text google_map">
					<span class="card-title">Вы можете найти нас по адресу:</span>
					<p class="card-title">Ляляля, у нас такой-то адрес!</p>
					<p><iframe class="google_map" src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d1343.9979511920865!2d40.86354470222039!3d47.64564646234606!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sru!2sru!4v1456778520424" frameborder="0" style="width:100%;height:330px;border:0px" allowfullscreen></iframe></p>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

mainpage/templates/mainpage/question.html
{% extends "mainpage/base.html" %}

{% block css-link %}
<link rel="stylesheet" type="text/css" href="/static/css/question.css">
{% endblock %}

{% block content %}
	 <!-- Новый вопрос -->
<div class="col s10">
	<div class="card-panel teal">
		<h1 class="header-title">Новый вопрос</h1>
	</div>
</div>

<div class="row post">
	<form method="POST" class="post-form">{% csrf_token %}
		<div class="col s6 offset-s3">
			<div class="card cyan darken-2">
				<div class="card-content white-text">
					<div class="row question">
						<div class="input-field col s12 ">
							<input id="id_title" name="title" type="text" required="" class="validate">
							<label for="first_name">Заголовок</label>
						</div>
					</div>
					<div class="row question">
						<div class="input-field col s12">
							<input id="id_description" name="description" type="text" required="" class="validate">
							<label for="mail">Описание</label>
						</div>
					</div>
				</div>
				<div class="card-action">
					<div class="row">
						<div class="col s2 offset-s5">
							<input type="submit" value="Отправить" class="waves-effect waves-light modal-close btn-flat left-register"/>
						</div>
					</div>
				</div>
			</div>
		</div>
	</form>
</div>


{% endblock %}

mainpage/templates/mainpage/questions.html
{% extends "mainpage/base.html" %}

{% block css-link %}
<link rel="stylesheet" type="text/css" href="/static/css/questions.css">
{% endblock %}

{% block content %}

<div class='row'>
	<div class="col s10 offset-s1 z-depth-3">

		<div class="card-panel blue lighten-1">
			<h1 class="header-title white-text">Ваши вопросы</h1>
			{% if context_dic.user.username %}
			<div class="col s1 offset-s11"><span class="white-text "><a class="btn-floating btn-large waves-effect waves-light red tooltipped z-depth-3" href='/questions/new/' data-tooltip="Добавить вопрос!"><i class="material-icons">add</i></a></span></div>
			{% endif %}
		</div>
	{% for question in context_dic.questions %}
		<a href={% url 'get_one_question' pk=question.pk %}>
			<div class="col s8 offset-s2 no_ident">
				<div class="card green darken-4">
					<div class="card-content white-text">
						<div class="row">
							<div class="col s12 offset-s1 bottom_margin_text">
								<p>{{ question.title }}</p>
							</div>
							<div class="col s8 offset-s1 bottom_margin_text">
								<p>{{ question.description }}</p>
							</div>
							<div class="col s6 bottom_margin_text">
								<p>{{ question.author_id }}</p>
							</div>
							<div class="col s6 bottom_margin_text">
								<p>{{ question.pub_date }}</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</a>
	{% endfor %}
	</div>
</div>

{% endblock %}

mainpage/templates/mainpage/show_question.html
{% extends "mainpage/base.html" %}

{% block css-link %}
<link rel="stylesheet" type="text/css" href="/static/css/show_question.css">
{% endblock %}

{% block content %}
<div class='row'>
	<div class="col s10 offset-s1 z-depth-3">
		<div class="col s12">
			<div class="card-panel teal">
				<h1 class="header-title">{{ context_dic.question.title }}</h1>
			</div>
		</div>
		<div class="col s6 offset-s6">
			<div class="card-panel teal center-text">
			{% if context_dic.user.username %}
			<span class="white-text">Добро пожаловать, {{ context_dic.user.username }} !!!</span>
			{% else %}
			<span class="white-text">Вы не зарегистрированы! Пожалуйста, войдеите через соцсети или зарегистрируйтесь.</span>
			{% endif %}
			</div>
		</div>
		<div class="col s8 offset-s2">
			<div class="card cyan">
				<div class="card-content white-text">
					<span class="card-title">{{ context_dic.question.title }}</span>
					<p>{{ context_dic.question.description }}</p>
					<h6>{{ context_dic.question.author_id }}</h6>
					<h6>{{ context_dic.question.pub_date }}</h6>
				</div>
			</div>
		</div>
		<div class="all_comments" id="all_comments">
			{% for comment in context_dic.comments %}
				<div class="col s6 offset-s3 no_ident">
					<div class="card blue">
						<div class="card-content white-text">
							<p>{{ comment.author_id }}</p>
							<h6>{{ comment.description|linebreaks }}</h6>
							<h6>{{ comment.pub_date|date:"Y m d H i" }}</h6>
						</div>
					</div>
				</div>

			{% empty %}
			<div class="row">
				<div class="col s6 offset-s3 no_ident">
					<div class="card blue">
						<div class="card-content white-text">
							<span class="card-title">Комментариев пока нет!</span>
						</div>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>

		<div class="col s6 offset-s3 z-depth-1">
			<div class="card cyan">
				<form method="POST" class="post-form">{% csrf_token %}
					<div class="input-field col s12">
						<textarea id="id_description" name="description"  class="materialize-textarea"></textarea>
						<label for="description">Ваш комментарий</label>
					</div>
					<div class="col s6 offset-s4">
						<input type="button" value="Отправить" class="waves-effect waves-light cyan darken-1 btn" id="post_ajax"/>
					</div>
				</form>
			</div>
		</div>

	</div>
</div>

{% endblock %}